### ISSUE TITLE
[Docs]: Deploy checklist

### ISSUE THREAD

**Issue by TomFern** [semaphoreci/semaphore#217]
### Type

Maintenance task

### What do you want to report?

Steps for initial deployment:
- [x] Remove API Spec as a category (#213)
- [x] Disable hash router and localstorage (in `future` key on `docusaurus.config.js`)
- [x] Enable search engine/robots indexing (set `noIndex: false` on `docusaurus.config.js`)
- [x] Enable continuous deployment
- [x] Deploy to `https://docs-v2.sxmoon.com/` (staging)
- [x] Review/debug any remaining UI issues or broken links
- [x] Setup and enable Algolia search (#214)
- [x] Index site and test search functionality

Once everything is working, deploy to production:
- [x] Add redirection rules (#157)
- [x] Deploy to `docs.semaphoreci.com`
- [x] Re-index/update Algolia search

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/semaphoreci/semaphore?tab=coc-ov-file)

**Comment by TomFern** [comment]
Production site deployed on https://docs-v2.semaphoreci.com/
